services:
  http-server:
    image: jonasal/nginx-certbot:latest
    env_file: 
      - ./nginx.env
    build:
      context: nginx
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d:ro
    links:
      - hello-server
    ports: 
      - "80:80"
      - "443:443"


  hello-server:
    build: .
    ports:
      - "3000:3000"
volumes:
  nginx_secrets:

